
# seeds for testing! :D


Post.create!([
  {title: "Harry Potter GOF poster/book-cover", body: "I just really love this book cover/poster! Also I am harry potter irl", user_id: 1},
  {title: "Was feeling cute today", body: "i am harry potter irl tho", user_id: 1},
  {title: "Me nd Haggy back in da OG times ", body: "Yeh we was coppin all the goods in the alley", user_id: 1},
  {title: "Hate these Guys", body: "fell asleep on the A train the other day...", user_id: 1},
  {title: "Good Ol Hogwarts", body: "This is my house irl", user_id: 1},
  {title: "Lol drank too much redbull today", body: "Get 2 Redbull 3$ at this link : www.redbool?2dolla.com", user_id: 2},
  {title: "I like frogs", body: "frogs are a good animal we should save the frogs from the environment", user_id: 2},
  {title: "miss you old perv", body: "rip perv man", user_id: 2},
  {title: "Why they keep fouling me?", body: "😀😃😄😁😆😅😂🤣☺️😇🙂🙃😉😍😘😗😙😋😛😝😜🤪🤨🧐🤓😎🤩😏😒😞😔😟😕🙁☹️😣😖😫😩😢😭😤😠😡🤬🤯😳😱😨😰😥😓🤗🤔🤭🤫🤥😶😐😑😬🙄😯😦😧😮😲😴🤤😪😵🤐🤢🤮🤧😷🤒🤕🤑🤠😈👿👹👺🤡💩👻💀☠️👽👾🤖🎃😺😸😹😻😼😽🙀😿😾🤲🤲🏻🤲🏼🤲🏽👐🏾🤲🏿👐👐🏻👐🏼👐🏽👐🏾👐🏿🙌🙌🏻🙌🏼🙌🏽🙌🏾🙌🏿👏👏🏻👏🏼👏🏽👏🏾👏🏿🤝👍👍🏻👍🏼👍🏽👍🏾👍🏿👎", user_id: 3},
  {title: "Cybron", body: "Built Different.", user_id: 3},
  {title: "Big Problems Need BIG solutins!", body: "stayed up late with the science department working on this one! Think were gonna solve a lot big problems here.", user_id: 4},
  {title: "A great moment", body: "Knock Knock\n\"whose there?\"\n\"farts mcgee\"\n\"ahahahhaah\"", user_id: 4},
  {title: "Cool Portrait", body: "This is cool come take a look everyone!", user_id: 5},
  {title: "Thats What She Said", body: "Classic quite by yours truly", user_id: 6},
  {title: "The Homies!", body: "My family here at Dunder Miff!", user_id: 6},
  {title: "Fierce Stare", body: "Passion/Fine Art", user_id: 7},
  {title: "Fine Art 1", body: "Fine Art Collection", user_id: 7},
  {title: "Two Master Pieces", body: "Me with my ART", user_id: 7}
])
FollowJoin.create!([
  {following_id: 3, followed_id: 1},
  {following_id: 3, followed_id: 2},
  {following_id: 4, followed_id: 2},
  {following_id: 4, followed_id: 1},
  {following_id: 4, followed_id: 3},
  {following_id: 5, followed_id: 1},
  {following_id: 5, followed_id: 2},
  {following_id: 5, followed_id: 4},
  {following_id: 5, followed_id: 3},
  {following_id: 6, followed_id: 1},
  {following_id: 6, followed_id: 3},
  {following_id: 6, followed_id: 5},
  {following_id: 7, followed_id: 2},
  {following_id: 7, followed_id: 3},
  {following_id: 7, followed_id: 1},
  {following_id: 1, followed_id: 3},
  {following_id: 1, followed_id: 5},
  {following_id: 1, followed_id: 2},
  {following_id: 1, followed_id: 6},
  {following_id: 1, followed_id: 7},
  {following_id: 2, followed_id: 5},
  {following_id: 2, followed_id: 1},
  {following_id: 2, followed_id: 7},
  {following_id: 2, followed_id: 4},
  {following_id: 3, followed_id: 6},
  {following_id: 3, followed_id: 5},
  {following_id: 3, followed_id: 7},
  {following_id: 6, followed_id: 2},
  {following_id: 6, followed_id: 7}
])
LikedPost.create!([
  {user_id: 2, post_id: 4},
  {user_id: 2, post_id: 2},
  {user_id: 2, post_id: 3},
  {user_id: 3, post_id: 4},
  {user_id: 3, post_id: 5},
  {user_id: 3, post_id: 3},
  {user_id: 3, post_id: 8},
  {user_id: 3, post_id: 7},
  {user_id: 4, post_id: 6},
  {user_id: 4, post_id: 7},
  {user_id: 4, post_id: 8},
  {user_id: 4, post_id: 1},
  {user_id: 4, post_id: 2},
  {user_id: 4, post_id: 9},
  {user_id: 4, post_id: 10},
  {user_id: 4, post_id: 5},
  {user_id: 4, post_id: 11},
  {user_id: 4, post_id: 12},
  {user_id: 5, post_id: 2},
  {user_id: 5, post_id: 1},
  {user_id: 5, post_id: 5},
  {user_id: 5, post_id: 7},
  {user_id: 5, post_id: 6},
  {user_id: 5, post_id: 12},
  {user_id: 6, post_id: 2},
  {user_id: 6, post_id: 5},
  {user_id: 6, post_id: 13},
  {user_id: 7, post_id: 2},
  {user_id: 7, post_id: 8},
  {user_id: 7, post_id: 6},
  {user_id: 7, post_id: 10},
  {user_id: 7, post_id: 9},
  {user_id: 7, post_id: 4},
  {user_id: 7, post_id: 5},
  {user_id: 7, post_id: 1},
  {user_id: 7, post_id: 18},
  {user_id: 2, post_id: 18},
  {user_id: 2, post_id: 17},
  {user_id: 2, post_id: 16},
  {user_id: 2, post_id: 13},
  {user_id: 2, post_id: 10},
  {user_id: 3, post_id: 14},
  {user_id: 3, post_id: 15},
  {user_id: 6, post_id: 10},
  {user_id: 6, post_id: 9},
  {user_id: 6, post_id: 17},
  {user_id: 6, post_id: 16},
  {user_id: 6, post_id: 7}
])
User.create!([
  {username: "harryPotter56", password_digest: "$2a$12$.0OqUmnFsUHJu9hclvgDb.3Y3l/lK1N2dPzLHZkUVuiYI.1se3.Im", bio: "yer a wizard harry"},
  {username: "legitNarutoIrl", password_digest: "$2a$12$vZ5bhHnd4Lx30c1Hr1D3sOmuaHhnaxDay6MGvg72KcIUGFmwsrKnC", bio: "Hokage 2020"},
  {username: "lebronJames23", password_digest: "$2a$12$2N4mLLtLQZmcu81Bir9hSu82DOkQkXIovd3Y4YvqP0nnL5aQLRwh6", bio: "GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT GOAT"},
  {username: "donaldTrump", password_digest: "$2a$12$vsxU53LyrT2HCp4b7aGbPetAVAxgEJgFM5Tzxgmztb2eEjas0Iqee", bio: "Presidente numero 1, stable genius numero 2! "},
  {username: "tyraBanks21", password_digest: "$2a$12$qQrhoatEU9Q6EkovB3ADz.905izEC.2L3EFTxPJXnJxjB1Ipp8oU.", bio: "I am Tyra $banks"},
  {username: "mscotts25", password_digest: "$2a$12$0JjTAGDmQjdNU2WBTBn0J.Tez7zCEU4kW9pLCcGq3INhkI14xrClm", bio: "worlds best boss"},
  {username: "squidward", password_digest: "$2a$12$zy/dxbcTQ7Dk6BDQ/am.7eTfAovextB3/LHjXYoFpMBCbOPnckcYi", bio: "Artist and Clarinet master. "}
])
ActiveStorage::Blob.create!([
  {key: "0ykc2l8y8vgwxtok3q3xgh2pvlue", filename: "harryPropic.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 78196, checksum: "ezZg5qLFaIAUMSwiSjYBUw=="},
  {key: "idht0qctitzmqsv47ekjhrrw6k5d", filename: "hpBookCOver.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 488575, checksum: "Wv49hrNwcDEOTYj641sMdQ=="},
  {key: "hb49c8gwgn2jbanv31vxuc2beyrd", filename: "hptrippy.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 81822, checksum: "708uSRcKXFPLXA9EoLxtng=="},
  {key: "6za0xcqn1o9yjxcyotraupvglkzk", filename: "hhaggy.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 329773, checksum: "8v4BmEJPZXmKXTLmeMHtkA=="},
  {key: "hx87auq51b4a21nhjekxrp505r9f", filename: "demontor.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 93345, checksum: "Xoq6QWPk3mWJNZBZ5xMTJQ=="},
  {key: "8mmswpc9odt0h61922w3vi647dbr", filename: "hwarts.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 144260, checksum: "FjTxkYPgUKRL4FDAsqGAUg=="},
  {key: "fgmlnfmupou0nnwhe0pr2kjs69f5", filename: "propicruto.png", content_type: "image/png", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 290010, checksum: "jmGpxBlQGadRjNxmF8S4hQ=="},
  {key: "qfcn8fho5i568ikwcqj0q9b5pn43", filename: "rutoRbull.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 231452, checksum: "oWUHen4aGrDddgF8h/1luA=="},
  {key: "f7ohdy5a11idbzf4u1gnx063wprf", filename: "gbunta.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 180048, checksum: "X3ShsfZJxcRB0FfTw8YNxQ=="},
  {key: "tffgluyxp12222z81hve9h8n6jg8", filename: "uncle j.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 125885, checksum: "VbnBXBSQxPLwElIpqKPFsQ=="},
  {key: "4hrbmqqig19g1jg5e3i7h02304j6", filename: "lbj pro.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 45498, checksum: "Ac+tHns8M3RW0ErEyuilkA=="},
  {key: "ugg5x97iyfkuzv3wjmvmn9rhdmma", filename: "lol.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 106071, checksum: "Pn+6Wbryl44zmrYKmgKwVQ=="},
  {key: "n6waqbc564qkh0oyrt5eww6qtuj1", filename: "cybron.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 126616, checksum: "FtSR26hpDFCtiowEVv7Gsw=="},
  {key: "bk27ykpyf2t84m4en0760bc1iaud", filename: "dpic.jpeg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 63330, checksum: "KJ1/WeDztTOR2m2RCmTLjQ=="},
  {key: "s27ckqh0f5mzw25vln2wib1wzokw", filename: "lololol.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 130732, checksum: "Xe6q0F6ltVr81vW0lksAFw=="},
  {key: "jfaz963msx0ilzkixdlvsq0soakd", filename: "xilo.jpeg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 481438, checksum: "f7LDOjcyTx4AdYahnC/XZg=="},
  {key: "ghnssxfald452pa4deqbmirldudw", filename: "tyraPro].jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 307851, checksum: "eSfxyocEeQyhCb2fcbDgZQ=="},
  {key: "nfsw65jlalcjp8i2e9v12oiazct1", filename: "artt.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 145149, checksum: "G5SN8xshF0ZfInLJm4KQ6A=="},
  {key: "qc12ubdpbu867td1j6i2cuf8ztag", filename: "MichaelScott.png", content_type: "image/png", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 123188, checksum: "NXp55b7+Wt7+sdEgUO2V/A=="},
  {key: "4bzknwv0a6gt8vjhgkgx1at6ionf", filename: "tahats].jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 78861, checksum: "7dm2D03wrqmMsQ8dXNv6fQ=="},
  {key: "9ckknp2tvgocvf6knkbfq213gmcs", filename: "officel.jpeg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 157216, checksum: "lgJ0nr59wHaCVaenJof0Aw=="},
  {key: "ef512jdk4cpr0mao0fav2ombux04", filename: "Squidward_Tentacles.png", content_type: "image/png", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 128408, checksum: "thLv1Xx9f0vgK3t8FfczyQ=="},
  {key: "5qfeykcfso4k4swtyu4gycmmtvim", filename: "Squidward_Tentacles.png", content_type: "image/png", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 128408, checksum: "thLv1Xx9f0vgK3t8FfczyQ=="},
  {key: "d4hpaiy5zqg483dn3enzwnmh8194", filename: "5cc57f221db4ee6052d8d45c64ddfbad.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 488750, checksum: "4ZxKXJ/kDXilr4Y+LVK3Aw=="},
  {key: "ec5wzewzn1j29srwr373zsdmpw9p", filename: "maxresdefault.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, byte_size: 173990, checksum: "ZefC6tZJ3rSya6vuDLCEdg=="}
])
ActiveStorage::Attachment.create!([
  {name: "pro_pic", record_type: "User", record_id: 1, blob_id: 1},
  {name: "featured_image", record_type: "Post", record_id: 1, blob_id: 2},
  {name: "featured_image", record_type: "Post", record_id: 2, blob_id: 3},
  {name: "featured_image", record_type: "Post", record_id: 3, blob_id: 4},
  {name: "featured_image", record_type: "Post", record_id: 4, blob_id: 5},
  {name: "featured_image", record_type: "Post", record_id: 5, blob_id: 6},
  {name: "pro_pic", record_type: "User", record_id: 2, blob_id: 7},
  {name: "featured_image", record_type: "Post", record_id: 6, blob_id: 8},
  {name: "featured_image", record_type: "Post", record_id: 7, blob_id: 9},
  {name: "featured_image", record_type: "Post", record_id: 8, blob_id: 10},
  {name: "pro_pic", record_type: "User", record_id: 3, blob_id: 11},
  {name: "featured_image", record_type: "Post", record_id: 9, blob_id: 12},
  {name: "featured_image", record_type: "Post", record_id: 10, blob_id: 13},
  {name: "pro_pic", record_type: "User", record_id: 4, blob_id: 14},
  {name: "featured_image", record_type: "Post", record_id: 11, blob_id: 15},
  {name: "featured_image", record_type: "Post", record_id: 12, blob_id: 16},
  {name: "pro_pic", record_type: "User", record_id: 5, blob_id: 17},
  {name: "featured_image", record_type: "Post", record_id: 13, blob_id: 18},
  {name: "pro_pic", record_type: "User", record_id: 6, blob_id: 19},
  {name: "featured_image", record_type: "Post", record_id: 14, blob_id: 20},
  {name: "featured_image", record_type: "Post", record_id: 15, blob_id: 21},
  {name: "pro_pic", record_type: "User", record_id: 7, blob_id: 22},
  {name: "featured_image", record_type: "Post", record_id: 16, blob_id: 23},
  {name: "featured_image", record_type: "Post", record_id: 17, blob_id: 24},
  {name: "featured_image", record_type: "Post", record_id: 18, blob_id: 25}
])
